export const SANKTIONEN: Record<number, { beschreibung: string; preis: string }> = {
  1:  { beschreibung: "Nicht Erscheinen bei wichtigen Events ohne Abmeldung", preis: "150.000$" },
  2:  { beschreibung: "Beleidigung Innerhalb der Familie", preis: "200.000$" },
  3:  { beschreibung: "Beleidigung außerhalb der Familie", preis: "250.000$" },
  4:  { beschreibung: "Funkpflicht Missachtet", preis: "50.000$" },
  5:  { beschreibung: "Kindisches Verhalten", preis: "100.000$" },
  6:  { beschreibung: "Aufstellung stören", preis: "100.000$" },
  7:  { beschreibung: "Bei der Kolonne pitten bzw. die Kolonne unterbrechen", preis: "100.000$" },
  8:  { beschreibung: "Ein Familienmitglied töten", preis: "500.000$" },
  9:  { beschreibung: "Schießen auf dem Anwesen", preis: "100.000$" },
  10: { beschreibung: "Auspark-punkt blockieren", preis: "50.000$" },
  11: { beschreibung: "Stress außerhalb der Familie provozieren", preis: "500.000$" },
  12: { beschreibung: "Kleiderordnung Missachtet", preis: "50.000$" },
  13: { beschreibung: "Gut der Familie verschenkt", preis: "150.000$" },
  14: { beschreibung: "Nicht Abgemeldet", preis: "50.000$" },
  15: { beschreibung: "Familie bzw. Familienmitglieder nicht ernst nehmen", preis: "200.000$" },
  16: { beschreibung: "Familie lächerlich dastehen lassen", preis: "Bloodout" },
  17: { beschreibung: "Falschverhalten", preis: "200.000$" },
  18: { beschreibung: "Befehl höherer missachtet", preis: "100.000$" },
  19: { beschreibung: "Weitergabe Interner Informationen", preis: "Bloodout" },
  20: { beschreibung: "Keine Waffe dabei gehabt", preis: "100.000$" },
  21: { beschreibung: "Familien bzw. Familienmitglieder zinken", preis: "250.000$" },
  22: { beschreibung: "Nicht bezahlen einer Sanktion nach 3 Tagen", preis: "250.000$ + Warn" },
  23: { beschreibung: "Nicht bezahlen einer Sanktion nach 1 Woche", preis: "500.000$" },
  24: { beschreibung: "Nicht bezahlen einer Sanktion nach 2 Wochen", preis: "Bloodout" },
  25: { beschreibung: "Das nicht zahlen von Wochenabgaben nach 1 Woche", preis: "250.000$ + Warn" },
  26: { beschreibung: "Das nicht zahlen der Wochenabgaben nach 2 Wochen", preis: "500.000$" },
  27: { beschreibung: "Das nicht zahlen der Wochenabgaben nach 3 Wochen", preis: "Bloodout" },
  28: { beschreibung: "Das ausziehen der Familien Kleidung", preis: "200.000$" },
};
